using Microsoft.CodeAnalysis.Text;
using Microsoft.Extensions.DependencyInjection.Scanner.Model;
using System.Text;

namespace Microsoft.Extensions.DependencyInjection.Scanner.Emission;

/// <summary>
/// Builds the final C# source string from a collection of registrations.
/// Operates on serializable strings produced during discovery.
/// </summary>
public static class SourceBuilder
{
    public static SourceText Build(IEnumerable<RegistrationDefinition> registrations)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("public static class ScannerRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    public static void AddScannedServices(this IServiceCollection services)");
        sb.AppendLine("    {");

        var sorted = registrations
            .OrderBy(r => r.ImplementationType)
            .ThenBy(r => r.ServiceType);

        foreach (var reg in sorted)
        {
            // Note: ServiceType and ImplementationType already include 'global::' 
            // due to SymbolDisplayFormat.FullyQualifiedFormat in discovery.
            sb.AppendLine($"        services.Add{reg.Lifetime}<{reg.ServiceType}, {reg.ImplementationType}>();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }
}
